### PR TITLE
worker: add header based authenticator

### PR DESCRIPTION
**Pull request by srenatus**

### CODE REVIEW

**Comment by srenatus** [comment]
Sorry didn't intend to that _just yet_. This might come later. 

Anyway, it would be nice to discuss if you'd be open to a PR with this functionality later...?

**Comment by sergiogarcia94** [comment]
Hi @srenatus, could you provide us a bit more information about this method of authentication?.
We got this flow ([token introspection](https://github.com/Tecsisa/foulkon/issues/93)) in our scope, maybe that helps you.
Anyway we are open to include new ways of authentication to foulkon, and this looks like a "Nice to Have" feature. 
Feel free to ask us anything on [gitter](https://gitter.im/Tecsisa/foulkon) and thx :smile:.

**Comment by srenatus** [comment]
@sergiogarcia94 sure, I'm happy to expand on our plans there. We, too, are using OIDC for authenticating users (via dex). For supporting other API clients, we've created a small service taking care of authenticating a request. Now, any request coming into our system goes through that service, and when the service is able to authenticate the requestor, it'll inject a header, saying which requestor (or "user", but it's not necessarily tied to a human) the request comes from. *That header* is then what foulkon-worker (with this feature added) uses to "authenticate" the request. (In quotes because it's trusting the header completely.)

authn_service_situation_foulkon

⏩ It's very similar to the [kubernetes authenticating proxy setup](https://kubernetes.io/docs/admin/authentication/#authenticating-proxy).

I'm frequenting your gitter channel (👋) already, and I'm aware of your solution to that problem; but from the various alternatives, this one stood out. (Compared to either not using dex, or adding the client creds flow to dex.) Also, we're probably going to add further means of request authentication, so having all that in a single service, which has only the responsibility of authenticating requests, makes sense for us.

**Comment by rsoletob** [comment]
@srenatus we agree with your solution, feel free to open an issue with your idea. Althought, it would be great to explain the security implications, for example, your foulkon service must be isolated and only accesible by a trustworthy system.

**Comment by srenatus** [comment]
@rsoletob thanks for the feedback. I'll ensure it'll be enclosed in the _real_ PR. ("Coming soon")

**Pull request closed without merging**
